### PR TITLE
Remove ansible.netcommon <5.0.0 dependency to permit install of the newest releases

### PR DESCRIPTION
**Pull request by gianmarco-mameli**
##### SUMMARY
Removed the upper offset of ansible.netcommon collection dependency to permit install of the newest releases
At this time the collection version is 6.1.1, so with the dependency <5.0.0 it's impossible to install with newer collections that have ansible.netcommon as dependency

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
All components

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Shourai** [comment]
Was just about to ask for the same thing.

Would 
```
dependencies:
  ansible.netcommon: '>=1.0.0'
```
the same as in dellemc.os9 be an issue for this collection?

**Comment by gianmarco-mameli** [comment]
Anyone can please review and approve this PR? I'm trying to build an image with some collections and this one breaks the env, thanks

**Comment by tanganellilore** [comment]
@prasadapr any news on it?

**Comment by marcomezzaro** [comment]
Hi, any update on this? thanks

**Comment by prasadapr** [comment]
Hi Team, sorry due to other priority issues, we are not able to check this ticket. Earlier due to other request we have modified the condition. 
As you mentioned, we will remove the condition and will submit and provide the new release version.

**Comment by prasadapr** [comment]
Hi @gianmarco-mameli, Thanks for closing the issue.

**Pull request closed without merging**
