### PR TITLE
Add a changelog fragment for PR #45

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add a changelog fragment for PR https://github.com/ansible-collections/dellemc.os10/pull/45

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @sc68cal , is this fragment fine for the PR?

**Comment by Andersson007** [comment]
@dharmaraj-gurusamy @gunasekaran-t can anyone release `v1.2.0` of the collection as it hasn't been released since the last year?

**Review by sc68cal — APPROVED** [review]

**Comment by sc68cal** [comment]
fragment looks good to me

**Comment by Andersson007** [comment]
@sc68cal thanks for reviewing!

**Pull request merged**
